import { ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import LogoImage from "../../../public/img/icon.png";
import ProfileImage from "../../../public/img/profile logo.png"; // Optional profile image

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body className="flex min-h-screen bg-gray-100 text-sm">
        {/* Sidebar */}
        <aside className="w-64 bg-blue-600 text-white flex flex-col items-center py-6 fixed h-screen z-10">
          <Image
            src={LogoImage}
            alt="Logo"
            width={80}
            height={80}
            className="mb-6"
          />
          <nav className="flex flex-col space-y-4 text-center w-full">
            <Link href="/home" className="hover:bg-blue-700 py-2">Аж ахуйн нэгжүүд</Link>
            <Link href="/orders" className="hover:bg-blue-700 py-2">Миний захиалга</Link>
            <Link href="/complaints" className="hover:bg-blue-700 py-2">Гомдол</Link>
          </nav>
          <div className="mt-auto text-xs text-center p-4">Help and Support</div>
        </aside>

        {/* Main content */}
        <main className="ml-64 flex-1 p-6">
          {/* Top bar */}
          <div className="flex justify-between items-center mb-6">
            {/* Search Bar (matched style) */}
            <div className="relative w-80">
              <input
                type="text"
                placeholder="Хайх . . ."
                className="w-full rounded-full px-4 py-2 border pl-10"
              />
              <button className="absolute right-2 top-1/2 -translate-y-1/2 text-blue-600">
                🔍
              </button>
            </div>

            {/* Profile */}
            <div className="flex items-center space-x-2">
              <Image
                src={ProfileImage}
                alt="Profile"
                width={36}
                height={36}
                className="rounded-full"
              />
              <span className="text-sm font-medium">Миний профайл</span>
            </div>
          </div>

          {children}
        </main>
      </body>
    </html>
  );
}
